name: CI Build

on: [push, pull_request]

env:
  PYTHON_VERISON_DEFAULT: "3.10"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      # see https://github.com/actions/checkout
      uses: actions/checkout@v4
    - name: Set up JDK
      # see https://github.com/actions/setup-java
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        java-package: jdk
    - name: Build with Maven
      run: |
        cd tools
        mvn -B package --file pom.xml
        cd ..
    - name: Setup Python Environment
      # see https://github.com/actions/setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERISON_DEFAULT }}
        architecture: 'x64'
    - name: Generate JSON Schema documentation
      run: |
        cd docgen/json
        ./gen.sh
    - name: Generate XML Schema documentation
      run: |
        cd docgen/xml
        ./gen.sh
    - name: Archive JSON Schema documentation
      # https://github.com/actions/upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: JSON-Schema-documentation
        path: docgen/json/docs
    - name: Archive XML Schema documentation
      # https://github.com/actions/upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: XML-Schema-documentation
        path: docgen/xml/docs
